ignore:
  - "internal/cfg/*.go"
  - "internal/logger/*.go"
  - "internal/control/*.go"
  - "main.go"
  - "cmd.go"

comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
